### ISSUE TITLE
java.lang.IllegalArgumentException: no such vertex in graph: <http://www.semanticweb.org/drkm/ontologies/2017/4/untitled-ontology-82#Disease>

### ISSUE THREAD

**Issue by karanthpallavi** [jgraph/jgraphx#88]
Hi,

Have formed a DefaultDirectedGraph like this:
public DirectedGraph<OWLEntity, DefaultEdge> OWLGraph = new DefaultDirectedGraph<OWLEntity, DefaultEdge>(DefaultEdge.class);

Have added vertices and edges,
Vertex list is printed as follows:
System.out.println(OWLGraph.vertexSet());

The list shows the vertex:
<http://www.semanticweb.org/drkm/ontologies/2017/4/untitled-ontology-82#Disease>

Am constructing all directed paths from the graph as follows:
AllDirectedPaths allPathsGraph = new AllDirectedPaths(toGraph.OWLGraph);

Here, OWLGraph is the default directed graph,

Next, i call getAllPaths from source vertex <http://www.semanticweb.org/drkm/ontologies/2017/4/untitled-ontology-82#Food> to destination vertex:
<http://www.semanticweb.org/drkm/ontologies/2017/4/untitled-ontology-82#Disease>

The stack trace shows the error as:
java.lang.IllegalArgumentException: no such vertex in graph: <http://www.semanticweb.org/drkm/ontologies/2017/4/untitled-ontology-82#Disease>
	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:132)
	at org.jgrapht.graph.AbstractBaseGraph.incomingEdgesOf(AbstractBaseGraph.java:365)
	at org.jgrapht.alg.AllDirectedPaths.edgeMinDistancesBackwards(AllDirectedPaths.java:158)
	at org.jgrapht.alg.AllDirectedPaths.getAllPaths(AllDirectedPaths.java:105)
	at org.jgrapht.alg.AllDirectedPaths.getAllPaths(AllDirectedPaths.java:69)
	at com.mycompany.semanticdistance.SemanticDistance.SemanticDistance(SemanticDistance.java:161)
	at com.mycompany.semanticdistance.SemanticDistance.loadOntology(SemanticDistance.java:136)
	at com.mycompany.semanticdistance.SemanticDistance.main(SemanticDistance.java:84)

May i know how to resolve this?
Kindly help.
Thanks much in advance

**Comment by davidjgraph** [comment]
That stack isn't ours, you need to find the project for the jgrapht project.
